---
- name: Configure Application Server
  hosts: app
  connection: local
  become: yes
  
  tasks:
    - name: Clone application code to host
      git:
        repo: https://github.com/skorik-kirill/test_task.git
        dest: /tmp/application
        update: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx Service
      service:
        name: nginx
        state: started
